services:


  kong:
    image: kong:latest
    container_name: kong
    restart: always
    ports:
      - "8000:8000" # Proxy port
      - "8001:8001" # Admin API port
      - "8443:8443" # Proxy HTTPS port
      - "8444:8444" # Admin API HTTPS port
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/config/kong.yml"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_JWT_SECRET: "b18e4adfc5d84177cd8c053e5baaf0913504dafd2f1448ea374614aa0262b312"
    volumes:
      - ./kong/config:/config
    labels:
      - "traefik.http.routers.kong.rule=PathPrefix(`/api`)"
      - "traefik.http.services.kong.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.kong.middlewares=strip-api-prefix"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      SUPABASE_URL: https://ofpxzaxgejzpkuzigqda.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcHh6YXhnZWp6cGt1emlncWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mjc5MzgsImV4cCI6MjA2NzIwMzkzOH0.YIOl55vTXzSC5jXVMt00GrOy5TdeU1pKwlE0MfTVapg
      JWT_SECRET: b18e4adfc5d84177cd8c053e5baaf0913504dafd2f1448ea374614aa0262b312



  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    container_name: analytics
    environment:
      - TRANSCRIPT_API=http://transcript:9997/get_cp
      - QUIZ_API=http://smartquiz:5000/api/v1/
      - REFL_API=http://reflection:3001/v1
      - CLASSROOM_API=http://classroom:9696
    labels:
      - "traefik.enable=false"

  classpartrecording:
    build:
      context: ./classpartrecording
      dockerfile: Dockerfile
    container_name: classpartrecording
    environment:
      - SESSION_API=http://session:9697/
      - TRANSCRIBE_API=http://transcribe:3940/transcribe
      - TRANSCRIPT_API=http://transcript:9997
      - RABBITMQ_HOST=rabbitmq
    labels:
      - "traefik.enable=false"
  transcript:
    build:
      context: ./transcript
      dockerfile: Dockerfile
    container_name: transcript
    environment:
      - SUPABASE_URL=https://zsmllqyzhduhazmmldca.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzbWxscXl6aGR1aGF6bW1sZGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODM3NzYsImV4cCI6MjA1Nzc1OTc3Nn0.WyG11IZRAdKS_kot73KlEMZPTILQwuAx1mUaJkI7zgw
    labels:
      - "traefik.enable=false"

  classroom:
    build:
      context: ./classroom
      dockerfile: Dockerfile
    container_name: classroom
    environment:
      - SUPABASE_URL=https://gxjyxmhtimrirswdxuhj.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4anl4bWh0aW1yaXJzd2R4dWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDU1MzksImV4cCI6MjA1ODAyMTUzOX0.QGsmk3OsTiPivnW38scbL1QpfjVk6N0_aFxlvujib8w
    labels:
      - "traefik.enable=false"

  session:
    build:
      context: ./session
      dockerfile: Dockerfile
    container_name: session
    environment:
      - SUPABASE_URL=https://zlmaxfrnzadneyrgrotm.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbWF4ZnJuemFkbmV5cmdyb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTY4NDEsImV4cCI6MjA1ODA5Mjg0MX0.SNUFijz1UbZEE_nvEdukjyPuPOAr2uJpXL_2gIO27tw
    labels:
      - "traefik.enable=false"

  transcribe:
    build:
      context: ./transcribe
      dockerfile: Dockerfile
    container_name: transcribe
    labels:
      - "traefik.enable=false"

  smartquiz:
    build:
      context: ./smartquiz
      dockerfile: Dockerfile
    container_name: smartquiz
    depends_on:
      smartquiz_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@smartquiz_db/quiz_db
    labels:
      - "traefik.enable=false"

  smartquiz_db:
    image: mysql
    container_name: smartquiz_db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - ./smartquiz/db/mysql-data:/var/lib/mysql
      - ./smartquiz/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    labels:
      - "traefik.enable=false"

  endquiz:
    build:
      context: ./endquiz
      dockerfile: Dockerfile
    container_name: endquiz
    restart: unless-stopped
    environment:
      - QUIZ_SERVICE_URL=http://smartquiz:5000/api/v1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=email_service
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_QUEUE=email_queue
    depends_on:
      smartquiz:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.enable=false"

  displayquiz:
    build:
      context: ./display_quiz
      dockerfile: Dockerfile
    container_name: displayquiz
    environment:
      - QUIZ_SERVICE_URL=http://smartquiz:5000
      - END_QUIZ_SERVICE_URL=http://endquiz:5001
    labels:
      - "traefik.enable=false"

