_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://auth-service:5001
    routes:
      - name: auth-route
        paths: [/auth]
        strip_path: true

  - name: review-service
    url: http://review-service:5003
    routes:
      - name: review-route
        paths: [/review-service]
        strip_path: true

  - name: scanner
    url: http://scanner:5004
    routes:
      - name: scanner-route
        paths: [/scanner]
        strip_path: true

  - name: upload-service
    url: http://upload-service:5007
    routes:
      - name: upload-route
        paths: [/upload-service]
        strip_path: false

  - name: analyse-results
    url: http://analyse-results:5008
    routes:
      - name: analyse-route
        paths: [/analyse-results]
        strip_path: true

  - name: compare-service
    url: http://compare-service:5010
    routes:
      - name: compare-route
        paths: [/compare]
        strip_path: true

  - name: ai-model
    url: http://ai-model:5020
    routes:
      - name: ai-route
        paths: [/ai]
        strip_path: false

  - name: document-storage-service
    url: http://document-storage-service:5009
    routes:
      - name: document-storage-route
        paths: [/document-storage-service]
        strip_path: true

  - name: history-service
    url: http://history-service:5030
    routes:
      - name: history-route
        paths: [/history]
        strip_path: false

plugins:
  # Global CORS Plugin
  - name: cors
    enabled: true
    config:
      origins: ["*"]
      methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD]
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers: [X-Auth-Token]
      credentials: true
      max_age: 3600
      preflight_continue: false

  

consumers:
  - username: login_server_issuer
    jwt_secrets:
      - key: auth_service
        algorithm: HS256
        secret: b18e4adfc5d84177cd8c053e5baaf0913504dafd2f1448ea374614aa0262b312
