version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8000"
    depends_on:
      - match-history-service
      - auth-service

  match-history-service:
    build: ./match-history-service
    ports:
      - "5001:5000"

  auth-service:
    build: ./auth-service
    ports:
      - "5002:5000"


# services:
#   session:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     image: yiluan2023/session:1.0
#     container_name: session
#     ports:
#      - "9697:9697"
#     environment:
#       - SUPABASE_URL=https://zlmaxfrnzadneyrgrotm.supabase.co
#       - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbWF4ZnJuemFkbmV5cmdyb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTY4NDEsImV4cCI6MjA1ODA5Mjg0MX0.SNUFijz1UbZEE_nvEdukjyPuPOAr2uJpXL_2gIO27tw
#     networks:
#      - my_shared_network
# networks:
#   my_shared_network:  # Define the shared network (should match the network in classpartrecording.yml)
#     external: true  # Use the same external network
