version: '3.8'

services:
  upload-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yiluan2023/upload-service:1.0
    container_name: upload-service
    ports:
      - "5007:5007"  # Match the port in your app.py
    environment:
      - SCANNER_URL=http://scanner-service:8080/scan  # Replace with actual service URLs
      - DOCUMENT_URL=http://document-service:8081/process
      - AI_URL=http://ai-service:8082/analyze

    networks:
      - my_shared_network
networks:
  my_shared_network:
    external: false
