services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yiluan2023/auth:1.0
    container_name: auth
    ports:
     - "5001:5001"
    environment:
      SUPABASE_URL: https://ofpxzaxgejzpkuzigqda.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcHh6YXhnZWp6cGt1emlncWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mjc5MzgsImV4cCI6MjA2NzIwMzkzOH0.YIOl55vTXzSC5jXVMt00GrOy5TdeU1pKwlE0MfTVapg
      JWT_SECRET: b18e4adfc5d84177cd8c053e5baaf0913504dafd2f1448ea374614aa0262b312
    networks:
      - my_shared_network
networks:
  my_shared_network:
    external: false
